# Generated by Django 5.1.4 on 2025-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지')),
                ('content', models.TextField(max_length=100, verbose_name='내용')),
                ('interest', models.IntegerField(default=0, verbose_name='관심도')),
                ('devtool', models.CharField(max_length=24, verbose_name='개발툴')),
            ],
        ),
    ]
