# Generated by Django 5.1.4 on 2025-01-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=200)),
            ],
        ),
    ]
