# Generated by Django 5.1.4 on 2025-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('MeloDrama', 'MeloDrama'), ('SF', 'SF'), ('Horror', 'Horror')], max_length=50),
        ),
    ]
