# Generated by Django 5.1.4 on 2025-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0002_alter_devtool_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='content',
            field=models.TextField(blank=True, max_length=400, verbose_name='내용'),
        ),
    ]
